import type { Metadata } from "next";
import Providers from "./providers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth, signOut } from "@/auth";
import AuthLinks from "./AuthLinks";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function HeaderAuthControls() {
  const session = await auth();
  const isAuthenticated = Boolean(session?.user);

  if (!isAuthenticated) {
    return <AuthLinks />;
  }

  return (
    <form
      action={async () => {
        "use server";
        await signOut({ redirectTo: "/signin" });
      }}
    >
      <button
        type="submit"
        className="rounded-md border border-white/20 px-3 py-1.5 text-sm font-medium text-zinc-100 transition-colors hover:bg-white/10 sm:px-4 sm:py-2"
      >
        Выйти
      </button>
    </form>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <header className="border-b border-white/10 bg-black/70">
            <div className="mx-auto flex h-14 w-full max-w-6xl items-center justify-between px-4 sm:h-16 sm:px-6 lg:px-8">
              <h1 className="text-base font-semibold tracking-tight text-zinc-100 sm:text-lg">
                Custom Story MMORPG
              </h1>
              <Suspense fallback={<AuthLinks />}>
                <HeaderAuthControls />
              </Suspense>
            </div>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
